name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.2.2
      with:
        # Always attempt to pull a newer version of the image
        pull: true
        # Do not use cache when building the image
        no-cache: true
      #run: docker build . --file Dockerfile --tag nextcloud-docker-apache-supervisor
